package economy

// This code was generated by a tool. Any changes may be overwritten

import (
    "encoding/json"

    playfab "github.com/dgkanatsios/playfabsdk-go/sdk"

    "github.com/mitchellh/mapstructure"
)

// AddInventoryItems add inventory items.
// https://api.playfab.com/Documentation/Economy/method/AddInventoryItems
func AddInventoryItems(settings *playfab.Settings, postData *AddInventoryItemsRequestModel, entityToken string) (*AddInventoryItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/AddInventoryItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &AddInventoryItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// CreateDraftItem creates a new item in the working catalog using provided metadata.
// https://api.playfab.com/Documentation/Economy/method/CreateDraftItem
func CreateDraftItem(settings *playfab.Settings, postData *CreateDraftItemRequestModel, entityToken string) (*CreateDraftItemResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/CreateDraftItem", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &CreateDraftItemResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// CreateUploadUrls creates one or more upload URLs which can be used by the client to upload raw file data.
// https://api.playfab.com/Documentation/Economy/method/CreateUploadUrls
func CreateUploadUrls(settings *playfab.Settings, postData *CreateUploadUrlsRequestModel, entityToken string) (*CreateUploadUrlsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/CreateUploadUrls", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &CreateUploadUrlsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// DeleteEntityItemReviews deletes all reviews, helpfulness votes, and ratings submitted by the entity specified.
// https://api.playfab.com/Documentation/Economy/method/DeleteEntityItemReviews
func DeleteEntityItemReviews(settings *playfab.Settings, postData *DeleteEntityItemReviewsRequestModel, entityToken string) (*DeleteEntityItemReviewsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/DeleteEntityItemReviews", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &DeleteEntityItemReviewsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// DeleteInventoryCollection delete an Inventory Collection
// https://api.playfab.com/Documentation/Economy/method/DeleteInventoryCollection
func DeleteInventoryCollection(settings *playfab.Settings, postData *DeleteInventoryCollectionRequestModel, entityToken string) (*DeleteInventoryCollectionResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/DeleteInventoryCollection", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &DeleteInventoryCollectionResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// DeleteInventoryItems delete inventory items
// https://api.playfab.com/Documentation/Economy/method/DeleteInventoryItems
func DeleteInventoryItems(settings *playfab.Settings, postData *DeleteInventoryItemsRequestModel, entityToken string) (*DeleteInventoryItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/DeleteInventoryItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &DeleteInventoryItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// DeleteItem removes an item from working catalog and all published versions from the public catalog.
// https://api.playfab.com/Documentation/Economy/method/DeleteItem
func DeleteItem(settings *playfab.Settings, postData *DeleteItemRequestModel, entityToken string) (*DeleteItemResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/DeleteItem", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &DeleteItemResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// ExecuteInventoryOperations execute a list of Inventory Operations
// https://api.playfab.com/Documentation/Economy/method/ExecuteInventoryOperations
func ExecuteInventoryOperations(settings *playfab.Settings, postData *ExecuteInventoryOperationsRequestModel, entityToken string) (*ExecuteInventoryOperationsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/ExecuteInventoryOperations", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &ExecuteInventoryOperationsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetCatalogConfig gets the configuration for the catalog.
// https://api.playfab.com/Documentation/Economy/method/GetCatalogConfig
func GetCatalogConfig(settings *playfab.Settings, postData *GetCatalogConfigRequestModel, entityToken string) (*GetCatalogConfigResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/GetCatalogConfig", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetCatalogConfigResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetDraftItem retrieves an item from the working catalog. This item represents the current working state of the item.
// https://api.playfab.com/Documentation/Economy/method/GetDraftItem
func GetDraftItem(settings *playfab.Settings, postData *GetDraftItemRequestModel, entityToken string) (*GetDraftItemResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/GetDraftItem", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetDraftItemResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetDraftItems retrieves a paginated list of the items from the draft catalog.
// https://api.playfab.com/Documentation/Economy/method/GetDraftItems
func GetDraftItems(settings *playfab.Settings, postData *GetDraftItemsRequestModel, entityToken string) (*GetDraftItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/GetDraftItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetDraftItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetEntityDraftItems retrieves a paginated list of the items from the draft catalog created by the Entity.
// https://api.playfab.com/Documentation/Economy/method/GetEntityDraftItems
func GetEntityDraftItems(settings *playfab.Settings, postData *GetEntityDraftItemsRequestModel, entityToken string) (*GetEntityDraftItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/GetEntityDraftItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetEntityDraftItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetEntityItemReview gets the submitted review for the specified item by the authenticated entity.
// https://api.playfab.com/Documentation/Economy/method/GetEntityItemReview
func GetEntityItemReview(settings *playfab.Settings, postData *GetEntityItemReviewRequestModel, entityToken string) (*GetEntityItemReviewResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/GetEntityItemReview", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetEntityItemReviewResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetInventoryCollectionIds get Inventory Collection Ids
// https://api.playfab.com/Documentation/Economy/method/GetInventoryCollectionIds
func GetInventoryCollectionIds(settings *playfab.Settings, postData *GetInventoryCollectionIdsRequestModel, entityToken string) (*GetInventoryCollectionIdsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/GetInventoryCollectionIds", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetInventoryCollectionIdsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetInventoryItems get current inventory items.
// https://api.playfab.com/Documentation/Economy/method/GetInventoryItems
func GetInventoryItems(settings *playfab.Settings, postData *GetInventoryItemsRequestModel, entityToken string) (*GetInventoryItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/GetInventoryItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetInventoryItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetItem retrieves an item from the public catalog.
// https://api.playfab.com/Documentation/Economy/method/GetItem
func GetItem(settings *playfab.Settings, postData *GetItemRequestModel, entityToken string) (*GetItemResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/GetItem", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetItemResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetItemContainers search for a given item and return a set of bundles and stores containing the item
// https://api.playfab.com/Documentation/Economy/method/GetItemContainers
func GetItemContainers(settings *playfab.Settings, postData *GetItemContainersRequestModel, entityToken string) (*GetItemContainersResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/GetItemContainers", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetItemContainersResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetItemModerationState gets the moderation state for an item, including the concern category and string reason.
// https://api.playfab.com/Documentation/Economy/method/GetItemModerationState
func GetItemModerationState(settings *playfab.Settings, postData *GetItemModerationStateRequestModel, entityToken string) (*GetItemModerationStateResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/GetItemModerationState", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetItemModerationStateResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetItemPublishStatus gets the status of a publish of an item.
// https://api.playfab.com/Documentation/Economy/method/GetItemPublishStatus
func GetItemPublishStatus(settings *playfab.Settings, postData *GetItemPublishStatusRequestModel, entityToken string) (*GetItemPublishStatusResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/GetItemPublishStatus", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetItemPublishStatusResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetItemReviews get a paginated set of reviews associated with the specified item.
// https://api.playfab.com/Documentation/Economy/method/GetItemReviews
func GetItemReviews(settings *playfab.Settings, postData *GetItemReviewsRequestModel, entityToken string) (*GetItemReviewsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/GetItemReviews", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetItemReviewsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetItemReviewSummary get a summary of all reviews associated with the specified item.
// https://api.playfab.com/Documentation/Economy/method/GetItemReviewSummary
func GetItemReviewSummary(settings *playfab.Settings, postData *GetItemReviewSummaryRequestModel, entityToken string) (*GetItemReviewSummaryResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/GetItemReviewSummary", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetItemReviewSummaryResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetItems retrieves items from the public catalog.
// https://api.playfab.com/Documentation/Economy/method/GetItems
func GetItems(settings *playfab.Settings, postData *GetItemsRequestModel, entityToken string) (*GetItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/GetItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetMicrosoftStoreAccessTokens gets the access tokens.
// https://api.playfab.com/Documentation/Economy/method/GetMicrosoftStoreAccessTokens
func GetMicrosoftStoreAccessTokens(settings *playfab.Settings, postData *GetMicrosoftStoreAccessTokensRequestModel, entityToken string) (*GetMicrosoftStoreAccessTokensResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/GetMicrosoftStoreAccessTokens", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetMicrosoftStoreAccessTokensResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetTransactionHistory get transaction history.
// https://api.playfab.com/Documentation/Economy/method/GetTransactionHistory
func GetTransactionHistory(settings *playfab.Settings, postData *GetTransactionHistoryRequestModel, entityToken string) (*GetTransactionHistoryResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/GetTransactionHistory", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetTransactionHistoryResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// PublishDraftItem initiates a publish of an item from the working catalog to the public catalog.
// https://api.playfab.com/Documentation/Economy/method/PublishDraftItem
func PublishDraftItem(settings *playfab.Settings, postData *PublishDraftItemRequestModel, entityToken string) (*PublishDraftItemResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/PublishDraftItem", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &PublishDraftItemResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// PurchaseInventoryItems purchase an item or bundle
// https://api.playfab.com/Documentation/Economy/method/PurchaseInventoryItems
func PurchaseInventoryItems(settings *playfab.Settings, postData *PurchaseInventoryItemsRequestModel, entityToken string) (*PurchaseInventoryItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/PurchaseInventoryItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &PurchaseInventoryItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// RedeemAppleAppStoreInventoryItems redeem items.
// https://api.playfab.com/Documentation/Economy/method/RedeemAppleAppStoreInventoryItems
func RedeemAppleAppStoreInventoryItems(settings *playfab.Settings, postData *RedeemAppleAppStoreInventoryItemsRequestModel, entityToken string) (*RedeemAppleAppStoreInventoryItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/RedeemAppleAppStoreInventoryItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &RedeemAppleAppStoreInventoryItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// RedeemGooglePlayInventoryItems redeem items.
// https://api.playfab.com/Documentation/Economy/method/RedeemGooglePlayInventoryItems
func RedeemGooglePlayInventoryItems(settings *playfab.Settings, postData *RedeemGooglePlayInventoryItemsRequestModel, entityToken string) (*RedeemGooglePlayInventoryItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/RedeemGooglePlayInventoryItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &RedeemGooglePlayInventoryItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// RedeemMicrosoftStoreInventoryItems redeem items.
// https://api.playfab.com/Documentation/Economy/method/RedeemMicrosoftStoreInventoryItems
func RedeemMicrosoftStoreInventoryItems(settings *playfab.Settings, postData *RedeemMicrosoftStoreInventoryItemsRequestModel, entityToken string) (*RedeemMicrosoftStoreInventoryItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/RedeemMicrosoftStoreInventoryItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &RedeemMicrosoftStoreInventoryItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// RedeemNintendoEShopInventoryItems redeem items.
// https://api.playfab.com/Documentation/Economy/method/RedeemNintendoEShopInventoryItems
func RedeemNintendoEShopInventoryItems(settings *playfab.Settings, postData *RedeemNintendoEShopInventoryItemsRequestModel, entityToken string) (*RedeemNintendoEShopInventoryItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/RedeemNintendoEShopInventoryItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &RedeemNintendoEShopInventoryItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// RedeemPlayStationStoreInventoryItems redeem items.
// https://api.playfab.com/Documentation/Economy/method/RedeemPlayStationStoreInventoryItems
func RedeemPlayStationStoreInventoryItems(settings *playfab.Settings, postData *RedeemPlayStationStoreInventoryItemsRequestModel, entityToken string) (*RedeemPlayStationStoreInventoryItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/RedeemPlayStationStoreInventoryItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &RedeemPlayStationStoreInventoryItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// RedeemSteamInventoryItems redeem items.
// https://api.playfab.com/Documentation/Economy/method/RedeemSteamInventoryItems
func RedeemSteamInventoryItems(settings *playfab.Settings, postData *RedeemSteamInventoryItemsRequestModel, entityToken string) (*RedeemSteamInventoryItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/RedeemSteamInventoryItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &RedeemSteamInventoryItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// ReportItem submit a report for an item, indicating in what way the item is inappropriate.
// https://api.playfab.com/Documentation/Economy/method/ReportItem
func ReportItem(settings *playfab.Settings, postData *ReportItemRequestModel, entityToken string) (*ReportItemResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/ReportItem", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &ReportItemResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// ReportItemReview submit a report for a review
// https://api.playfab.com/Documentation/Economy/method/ReportItemReview
func ReportItemReview(settings *playfab.Settings, postData *ReportItemReviewRequestModel, entityToken string) (*ReportItemReviewResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/ReportItemReview", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &ReportItemReviewResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// ReviewItem creates or updates a review for the specified item.
// https://api.playfab.com/Documentation/Economy/method/ReviewItem
func ReviewItem(settings *playfab.Settings, postData *ReviewItemRequestModel, entityToken string) (*ReviewItemResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/ReviewItem", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &ReviewItemResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// SearchItems executes a search against the public catalog using the provided search parameters and returns a set of paginated
// results.
// https://api.playfab.com/Documentation/Economy/method/SearchItems
func SearchItems(settings *playfab.Settings, postData *SearchItemsRequestModel, entityToken string) (*SearchItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/SearchItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &SearchItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// SetItemModerationState sets the moderation state for an item, including the concern category and string reason.
// https://api.playfab.com/Documentation/Economy/method/SetItemModerationState
func SetItemModerationState(settings *playfab.Settings, postData *SetItemModerationStateRequestModel, entityToken string) (*SetItemModerationStateResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/SetItemModerationState", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &SetItemModerationStateResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// SubmitItemReviewVote submit a vote for a review, indicating whether the review was helpful or unhelpful.
// https://api.playfab.com/Documentation/Economy/method/SubmitItemReviewVote
func SubmitItemReviewVote(settings *playfab.Settings, postData *SubmitItemReviewVoteRequestModel, entityToken string) (*SubmitItemReviewVoteResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/SubmitItemReviewVote", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &SubmitItemReviewVoteResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// SubtractInventoryItems subtract inventory items.
// https://api.playfab.com/Documentation/Economy/method/SubtractInventoryItems
func SubtractInventoryItems(settings *playfab.Settings, postData *SubtractInventoryItemsRequestModel, entityToken string) (*SubtractInventoryItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/SubtractInventoryItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &SubtractInventoryItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// TakedownItemReviews submit a request to takedown one or more reviews.
// https://api.playfab.com/Documentation/Economy/method/TakedownItemReviews
func TakedownItemReviews(settings *playfab.Settings, postData *TakedownItemReviewsRequestModel, entityToken string) (*TakedownItemReviewsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/TakedownItemReviews", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &TakedownItemReviewsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// TransferInventoryItems transfer inventory items.
// https://api.playfab.com/Documentation/Economy/method/TransferInventoryItems
func TransferInventoryItems(settings *playfab.Settings, postData *TransferInventoryItemsRequestModel, entityToken string) (*TransferInventoryItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/TransferInventoryItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &TransferInventoryItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// UpdateCatalogConfig updates the configuration for the catalog.
// https://api.playfab.com/Documentation/Economy/method/UpdateCatalogConfig
func UpdateCatalogConfig(settings *playfab.Settings, postData *UpdateCatalogConfigRequestModel, entityToken string) (*UpdateCatalogConfigResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/UpdateCatalogConfig", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &UpdateCatalogConfigResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// UpdateDraftItem update the metadata for an item in the working catalog.
// https://api.playfab.com/Documentation/Economy/method/UpdateDraftItem
func UpdateDraftItem(settings *playfab.Settings, postData *UpdateDraftItemRequestModel, entityToken string) (*UpdateDraftItemResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Catalog/UpdateDraftItem", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &UpdateDraftItemResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// UpdateInventoryItems update inventory items
// https://api.playfab.com/Documentation/Economy/method/UpdateInventoryItems
func UpdateInventoryItems(settings *playfab.Settings, postData *UpdateInventoryItemsRequestModel, entityToken string) (*UpdateInventoryItemsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Inventory/UpdateInventoryItems", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &UpdateInventoryItemsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}



