package profiles

// This code was generated by a tool. Any changes may be overwritten

import (
    "encoding/json"

    playfab "github.com/dgkanatsios/playfabsdk-go/sdk"

    "github.com/mitchellh/mapstructure"
)

// GetGlobalPolicy gets the global title access policy
// https://api.playfab.com/Documentation/Profiles/method/GetGlobalPolicy
func GetGlobalPolicy(settings *playfab.Settings, postData *GetGlobalPolicyRequestModel, entityToken string) (*GetGlobalPolicyResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Profile/GetGlobalPolicy", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetGlobalPolicyResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetProfile retrieves the entity's profile.
// https://api.playfab.com/Documentation/Profiles/method/GetProfile
func GetProfile(settings *playfab.Settings, postData *GetEntityProfileRequestModel, entityToken string) (*GetEntityProfileResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Profile/GetProfile", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetEntityProfileResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetProfiles retrieves the entity's profile.
// https://api.playfab.com/Documentation/Profiles/method/GetProfiles
func GetProfiles(settings *playfab.Settings, postData *GetEntityProfilesRequestModel, entityToken string) (*GetEntityProfilesResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Profile/GetProfiles", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetEntityProfilesResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// GetTitlePlayersFromMasterPlayerAccountIds retrieves the title player accounts associated with the given master player account.
// https://api.playfab.com/Documentation/Profiles/method/GetTitlePlayersFromMasterPlayerAccountIds
func GetTitlePlayersFromMasterPlayerAccountIds(settings *playfab.Settings, postData *GetTitlePlayersFromMasterPlayerAccountIdsRequestModel, entityToken string) (*GetTitlePlayersFromMasterPlayerAccountIdsResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Profile/GetTitlePlayersFromMasterPlayerAccountIds", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &GetTitlePlayersFromMasterPlayerAccountIdsResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// SetGlobalPolicy sets the global title access policy
// https://api.playfab.com/Documentation/Profiles/method/SetGlobalPolicy
func SetGlobalPolicy(settings *playfab.Settings, postData *SetGlobalPolicyRequestModel, entityToken string) (*SetGlobalPolicyResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Profile/SetGlobalPolicy", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &SetGlobalPolicyResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// SetProfileLanguage updates the entity's language. The precedence hierarchy for communication to the player is Title Player Account
// language, Master Player Account language, and then title default language if the first two aren't set or supported.
// https://api.playfab.com/Documentation/Profiles/method/SetProfileLanguage
func SetProfileLanguage(settings *playfab.Settings, postData *SetProfileLanguageRequestModel, entityToken string) (*SetProfileLanguageResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Profile/SetProfileLanguage", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &SetProfileLanguageResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}

// SetProfilePolicy sets the profiles access policy
// https://api.playfab.com/Documentation/Profiles/method/SetProfilePolicy
func SetProfilePolicy(settings *playfab.Settings, postData *SetEntityProfilePolicyRequestModel, entityToken string) (*SetEntityProfilePolicyResponseModel, error) {
    if entityToken == "" {
        return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
    }
    b, errMarshal := json.Marshal(postData)
    if errMarshal != nil {
        return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
    }

    sourceMap, err := playfab.Request(settings, b, "/Profile/SetProfilePolicy", "X-EntityToken", entityToken)
    if err != nil {
        return nil, err
    }
    
    result := &SetEntityProfilePolicyResponseModel{}

    config := mapstructure.DecoderConfig{
        DecodeHook: playfab.StringToDateTimeHook,
        Result:     result,
    }
    
    decoder, errDecoding := mapstructure.NewDecoder(&config)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }
   
    errDecoding = decoder.Decode(sourceMap)
    if errDecoding != nil {
        return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
    }

    return result, nil
}



