package data

// This code was generated by a tool. Any changes may be overwritten

import (
	"encoding/json"

	playfab "github.com/dgkanatsios/playfabsdk-go/sdk"

	"github.com/mitchellh/mapstructure"
)

// AbortFileUploads abort pending file uploads to an entity's profile.
// https://api.playfab.com/Documentation/Data/method/AbortFileUploads
func AbortFileUploads(settings *playfab.Settings, postData *AbortFileUploadsRequestModel, entityToken string) (*AbortFileUploadsResponseModel, error) {
	if entityToken == "" {
		return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
	}
	b, errMarshal := json.Marshal(postData)
	if errMarshal != nil {
		return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
	}

	sourceMap, err := playfab.Request(settings, b, "/File/AbortFileUploads", "X-EntityToken", entityToken)
	if err != nil {
		return nil, err
	}

	result := &AbortFileUploadsResponseModel{}

	config := mapstructure.DecoderConfig{
		DecodeHook: playfab.StringToDateTimeHook,
		Result:     result,
	}

	decoder, errDecoding := mapstructure.NewDecoder(&config)
	if errDecoding != nil {
		return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
	}

	errDecoding = decoder.Decode(sourceMap)
	if errDecoding != nil {
		return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
	}

	return result, nil
}

// DeleteFiles delete files on an entity's profile.
// https://api.playfab.com/Documentation/Data/method/DeleteFiles
func DeleteFiles(settings *playfab.Settings, postData *DeleteFilesRequestModel, entityToken string) (*DeleteFilesResponseModel, error) {
	if entityToken == "" {
		return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
	}
	b, errMarshal := json.Marshal(postData)
	if errMarshal != nil {
		return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
	}

	sourceMap, err := playfab.Request(settings, b, "/File/DeleteFiles", "X-EntityToken", entityToken)
	if err != nil {
		return nil, err
	}

	result := &DeleteFilesResponseModel{}

	config := mapstructure.DecoderConfig{
		DecodeHook: playfab.StringToDateTimeHook,
		Result:     result,
	}

	decoder, errDecoding := mapstructure.NewDecoder(&config)
	if errDecoding != nil {
		return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
	}

	errDecoding = decoder.Decode(sourceMap)
	if errDecoding != nil {
		return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
	}

	return result, nil
}

// FinalizeFileUploads finalize file uploads to an entity's profile.
// https://api.playfab.com/Documentation/Data/method/FinalizeFileUploads
func FinalizeFileUploads(settings *playfab.Settings, postData *FinalizeFileUploadsRequestModel, entityToken string) (*FinalizeFileUploadsResponseModel, error) {
	if entityToken == "" {
		return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
	}
	b, errMarshal := json.Marshal(postData)
	if errMarshal != nil {
		return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
	}

	sourceMap, err := playfab.Request(settings, b, "/File/FinalizeFileUploads", "X-EntityToken", entityToken)
	if err != nil {
		return nil, err
	}

	result := &FinalizeFileUploadsResponseModel{}

	config := mapstructure.DecoderConfig{
		DecodeHook: playfab.StringToDateTimeHook,
		Result:     result,
	}

	decoder, errDecoding := mapstructure.NewDecoder(&config)
	if errDecoding != nil {
		return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
	}

	errDecoding = decoder.Decode(sourceMap)
	if errDecoding != nil {
		return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
	}

	return result, nil
}

// GetFiles retrieves file metadata from an entity's profile.
// https://api.playfab.com/Documentation/Data/method/GetFiles
func GetFiles(settings *playfab.Settings, postData *GetFilesRequestModel, entityToken string) (*GetFilesResponseModel, error) {
	if entityToken == "" {
		return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
	}
	b, errMarshal := json.Marshal(postData)
	if errMarshal != nil {
		return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
	}

	sourceMap, err := playfab.Request(settings, b, "/File/GetFiles", "X-EntityToken", entityToken)
	if err != nil {
		return nil, err
	}

	result := &GetFilesResponseModel{}

	config := mapstructure.DecoderConfig{
		DecodeHook: playfab.StringToDateTimeHook,
		Result:     result,
	}

	decoder, errDecoding := mapstructure.NewDecoder(&config)
	if errDecoding != nil {
		return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
	}

	errDecoding = decoder.Decode(sourceMap)
	if errDecoding != nil {
		return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
	}

	return result, nil
}

// GetObjects retrieves objects from an entity's profile.
// https://api.playfab.com/Documentation/Data/method/GetObjects
func GetObjects(settings *playfab.Settings, postData *GetObjectsRequestModel, entityToken string) (*GetObjectsResponseModel, error) {
	if entityToken == "" {
		return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
	}
	b, errMarshal := json.Marshal(postData)
	if errMarshal != nil {
		return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
	}

	sourceMap, err := playfab.Request(settings, b, "/Object/GetObjects", "X-EntityToken", entityToken)
	if err != nil {
		return nil, err
	}

	result := &GetObjectsResponseModel{}

	config := mapstructure.DecoderConfig{
		DecodeHook: playfab.StringToDateTimeHook,
		Result:     result,
	}

	decoder, errDecoding := mapstructure.NewDecoder(&config)
	if errDecoding != nil {
		return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
	}

	errDecoding = decoder.Decode(sourceMap)
	if errDecoding != nil {
		return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
	}

	return result, nil
}

// InitiateFileUploads initiates file uploads to an entity's profile.
// https://api.playfab.com/Documentation/Data/method/InitiateFileUploads
func InitiateFileUploads(settings *playfab.Settings, postData *InitiateFileUploadsRequestModel, entityToken string) (*InitiateFileUploadsResponseModel, error) {
	if entityToken == "" {
		return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
	}
	b, errMarshal := json.Marshal(postData)
	if errMarshal != nil {
		return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
	}

	sourceMap, err := playfab.Request(settings, b, "/File/InitiateFileUploads", "X-EntityToken", entityToken)
	if err != nil {
		return nil, err
	}

	result := &InitiateFileUploadsResponseModel{}

	config := mapstructure.DecoderConfig{
		DecodeHook: playfab.StringToDateTimeHook,
		Result:     result,
	}

	decoder, errDecoding := mapstructure.NewDecoder(&config)
	if errDecoding != nil {
		return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
	}

	errDecoding = decoder.Decode(sourceMap)
	if errDecoding != nil {
		return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
	}

	return result, nil
}

// SetObjects sets objects on an entity's profile.
// https://api.playfab.com/Documentation/Data/method/SetObjects
func SetObjects(settings *playfab.Settings, postData *SetObjectsRequestModel, entityToken string) (*SetObjectsResponseModel, error) {
	if entityToken == "" {
		return nil, playfab.NewCustomError("entityToken should not be an empty string", playfab.ErrorGeneric)
	}
	b, errMarshal := json.Marshal(postData)
	if errMarshal != nil {
		return nil, playfab.NewCustomError(errMarshal.Error(), playfab.ErrorMarshal)
	}

	sourceMap, err := playfab.Request(settings, b, "/Object/SetObjects", "X-EntityToken", entityToken)
	if err != nil {
		return nil, err
	}

	result := &SetObjectsResponseModel{}

	config := mapstructure.DecoderConfig{
		DecodeHook: playfab.StringToDateTimeHook,
		Result:     result,
	}

	decoder, errDecoding := mapstructure.NewDecoder(&config)
	if errDecoding != nil {
		return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
	}

	errDecoding = decoder.Decode(sourceMap)
	if errDecoding != nil {
		return nil, playfab.NewCustomError(errDecoding.Error(), playfab.ErrorDecoding)
	}

	return result, nil
}
